### ISSUE TITLE
`OSName` and `OSVersion` not part of `params.BootstrapInstance`

### ISSUE THREAD

**Issue by rafalgalaw** [cloudbase/garm#178]
### Current Behaviour:

Right now only the `OSType` and `OSArch` are passed via `params.BootstrapInstance` to the `CreateInstance` method of a garm-provider.

### Suggestion / Question:

Is there any reason why the `OSName` and `OSVersion` of a pool are not passed as well via `params.BootstrapInstance`? 
For example when converting any type of VM or Pod from a cloud vendors api back to a `params.Instance`, `OSName` and `OSVersion` need to be set. This requires some kind of extra api request to the cloud vendor (like in the openstack provider) or in case of our current kubernetes provider setup storing the `OSName` and `OSVersion` in the image tag itself and extracting it from there, because at runtime we have no chance of getting this metadata information.
But if `OSName` and `OSVersion` would come with `params.BootstrapInstance`, one could just store the information in a pod label and access it from there.

**Comment by gabriel-samfira** [comment]
Hi @rafalgalaw 

The idea was that pools must be aware of the OS and architecture (because that's all we care about in reality, to be able to select the proper tools) of the pool, but the image itself would dictate the actual OS Name and OS version. This is why providers send back that info as part of the instance create/list response. This is because each provider has a different idea about what an `image` is and how it handles it.

The longer term goal was to have the userdata phone home that info once the machine (vm, container, etc)  booted, and not scrape the image metadata from the provider (because even that can be erroneous).

> For example when converting any type of VM or Pod from a cloud vendors api back to a params.Instance, OSName and OSVersion need to be set.

The OS name and versions are just informational. We don't act on them at all. The provider can choose to send back empty values and all should be fine. It would just be some missing info when listing runners [and a log message with a warning](https://github.com/cloudbase/garm/blob/b1dd54c07e989d5335cd864cedb0efcbfee74dc0/runner/providers/external/external.go#L58-L61).

>  This requires some kind of extra api request to the cloud vendor (like in the openstack provider) or in case of our current kubernetes provider setup storing the OSName and OSVersion in the image tag itself and extracting it from there, because at runtime we have no chance of getting this metadata information.

Your k8s provider should work fine even if it doesn't provide this info. On the other hand, you could retrieve this info from the spun up container by reading `/etc/os-release`. If it's not there, you're most likely dealing with a `scratch` image. But as mentioned, it is not strictly needed. It's just something you could do if you wish.

You could even send back placeholder values like `OSName: unknown` and `OSVersion: N/A`.

Let me know if this helps, and apologies about the late reply. You never know how much email you get every day, until you miss 1 week's worth of them :smile:.

**Comment by rafalgalaw** [comment]
Thanks for the explaination, i think that makes sense!
