### ISSUE TITLE
cannot add github credentials through garm-cli

### ISSUE THREAD

**Issue by pathcl** [cloudbase/garm#258]
Dear folks,

I'm trying to give it a try to garm following it's quickstart [here](https://github.com/cloudbase/garm/blob/main/doc/quickstart.md#adding-credentials)

However:

```
garm $ wget -q -O - https://github.com/cloudbase/garm/releases/download/v0.1.4/garm-cli-linux-amd64.tgz |  sudo tar xzf - -C /usr/local/bin/

garm $ garm-cli version
v0.1.4

garm $ garm-cli github credentials add   --name gabriel   --description "GitHub PAT for user gabriel"   --auth-type pat   --pat-oauth-token sometoken   --endpoint github.com
Error: unknown command "github" for "garm-cli"
Run 'garm-cli --help' for usage.

garm $ garm-cli github credentials add   --name gabriel_app   --description "Github App with access to repos"   --endpoint github.com   --auth-type app   --app-id 1111   --app-installation-id 1111   --private-key-path /home/pathcl/go/src/github.com/pathcl/garm/private-key-runners.pem
Error: unknown command "github" for "garm-cli"
Run 'garm-cli --help' for usage.

```

Am I missing something? thanks in advance

**Comment by gabriel-samfira** [comment]
Hi @pathcl 

The README in the `main` branch is in flux and refers to the code not yet released. I need to do a better job at organizing the docs :sweat_smile: . To set up the latest "stable" release, see the docs in the v0.1.4 tag:

https://github.com/cloudbase/garm/blob/v0.1.4/doc/quickstart.md

But even that has a few typos in it :disappointed:  (something I will try to avoid starting with the next release). When following the guide from the above link, please check that the download links point to v0.1.4 instead of v0.1.3.

That being said, if you're willing to try out the latest main branch (should be relatively stable, with a bunch of improvements), that would also be great. There is a simple [building from source](https://github.com/cloudbase/garm/blob/v0.1.4/doc/building_from_source.md) doc.

**Comment by gabriel-samfira** [comment]
If you're building from source, I recommend you have docker or podman installed and to run the:

```bash
make build-static
```

command.

**Comment by gabriel-samfira** [comment]
going to close this. Feel free to reopen if needed.
