### ISSUE TITLE
garm-cli pool update does not update tags of idle runners

### ISSUE THREAD

**Issue by rgl** [cloudbase/garm#293]
it seems `garm-cli pool update --tags` does not update the tags on the runners that are idle. for example, running:

```bash
./garm-cli pool update \
  --min-idle-runners 1 \
  --max-runners 3 \
  --tags self-hosted,azure,amd64,ubuntu-22.04 \
  "$pool_id"
```

and going into the github runners page, the runner still shows as:

![image](https://github.com/user-attachments/assets/ba050c44-7df8-42fd-bed4-6b2f70e2edcb)

**Comment by gabriel-samfira** [comment]
That is expected behavior. The tags apply to new runners. Given the high churn rate of runners, it didn't feel like it made sense to spend the extra API calls to reset the runner labels. Especially considering that once set, they rarely change. It also makes the code simpler. We don't have to compare existing, remove extra tags, add missing tags, etc. For those few runners that were created before the tags change, it was always easier to remove them and allow garm to recreate them with the new tags.

If this is something you need, we can add it.

**Comment by rgl** [comment]
ah that sounds reasonable, I will retract my request.
